server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/habuma/cloud-native-spring-service-registry
          search-paths:
            - config
